import {
  LayoutDashboardIcon,
  StarIcon,
  UsersIcon,
  VideoIcon,
} from 'lucide-react'
import { Inter } from 'next/font/google'
import Link from 'next/link'
// import { LuLayoutDashboard } from 'react-icons/lu'
// import { AiOutlineVideoCameraAdd } from 'react-icons/ai'
// import { MdOutlineCategory } from 'react-icons/md'
// import { PiUsersThreeBold } from 'react-icons/pi'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <div className='flex'>
        <aside className='bg-black w-[20%] fixed top-0 left-0 bottom-0 z-50'>
          <ul className='text-white p-6'>
            <Link href='/admin/dashboard'>
              <li className='hover:bg-gray-700 rounded-md p-2 flex items-center gap-2'>
                <LayoutDashboardIcon /> Dashboard
              </li>
            </Link>
            <Link href='/admin/dashboard/new'>
              <li className='hover:bg-gray-700 rounded-md p-2 flex items-center gap-2'>
                <VideoIcon /> New Course
              </li>
            </Link>
            <Link href='/admin/dashboard/category'>
              <li className='hover:bg-gray-700 rounded-md p-2 flex items-center gap-2'>
                <StarIcon /> New Category
              </li>
            </Link>
            <Link href='/admin/dashboard/manage-users'>
              <li className='hover:bg-gray-700 rounded-md p-2 flex items-center gap-2'>
                <UsersIcon /> Manage Users
              </li>
            </Link>
          </ul>
        </aside>
        <div className='p-10 ml-[20%]'>{children}</div>
      </div>
    </>
  )
}
